import { Router } from 'express'
import { requireAdmin } from '../middleware/authMiddleware.js'
import { adminData } from '../controllers/adminController.js'
import { createWard, declareWard, deleteWard, importWards, reopenWard, resetWards, updateWard } from '../controllers/wardController.js'
import { createCandidate, deleteCandidate, importCandidates, resetCandidates, setCandidateImage } from '../controllers/candidateController.js'
import { deleteResult, deleteWardResults, importResults, resetResults, setResult } from '../controllers/resultController.js'
import { clearSchedule, setElection, setResultDeclaration } from '../controllers/settingsController.js'

/** Super Admin API — every route requires a valid session token. */
const router = Router()
router.use(requireAdmin)

router.get('/data', adminData)

// Ward Master
router.post('/wards/import', importWards)
router.post('/wards', createWard)
router.put('/wards/:wardNo', updateWard)
router.delete('/wards/:wardNo/results', deleteWardResults)
router.delete('/wards/:wardNo', deleteWard)
router.delete('/wards', resetWards)
router.post('/wards/:wardNo/declare', declareWard)
router.post('/wards/:wardNo/reopen', reopenWard)

// Candidate Master (profiles; IDs are generated by the server)
router.post('/candidates/import', importCandidates)
router.post('/candidates', createCandidate)
router.put('/candidates/:id/image', setCandidateImage)
router.delete('/candidates/:id', deleteCandidate)
router.delete('/candidates', resetCandidates)

// Result data (votes), keyed by the candidate's database id
router.post('/results/import', importResults)
router.put('/results/:id', setResult)
router.delete('/results/:id', deleteResult)
router.delete('/results', resetResults)

// Election schedule
router.put('/settings/election', setElection)
router.put('/settings/result-declaration', setResultDeclaration)
router.delete('/settings', clearSchedule)

export default router
