import mongoose from 'mongoose'

/** Same candidate in the same ward is matched on this key (case/space-insensitive name). */
export const nameKeyOf = (name) => String(name ?? '').trim().replace(/\s+/g, ' ').toLowerCase()

/**
 * Candidate Master: profile information only. Votes live in the Result collection and the
 * winner is never stored: it is derived from the results when the ward is declared.
 *
 * `candidateId` is generated by the server (see utils/candidateId.js) and is unique. It is
 * null only for records migrated from older data whose generated ID collided with another
 * candidate; the admin panel shows those as Candidate ID conflicts.
 */
const candidateSchema = new mongoose.Schema(
  {
    candidateId: { type: String, default: null, trim: true },
    name: { type: String, required: true, trim: true, maxlength: 120 },
    nameKey: { type: String, required: true },
    party: { type: String, required: true, trim: true, maxlength: 80 },
    wardNo: { type: Number, required: true, min: 1, index: true },
    /** Resized photo as a data URL; served separately so lists stay small. */
    image: { type: String, default: null, select: false },
    hasImage: { type: Boolean, default: false },
  },
  { timestamps: true },
)

candidateSchema.index({ candidateId: 1 }, { unique: true, partialFilterExpression: { candidateId: { $type: 'string' } } })
candidateSchema.index({ wardNo: 1, nameKey: 1 })
candidateSchema.index({ name: 1 })

export const Candidate = mongoose.models.Candidate ?? mongoose.model('Candidate', candidateSchema)
