import { useMemo, useState } from 'react'
import { AlertTriangle, Eye, Plus } from 'lucide-react'
import AdminPageHeader from '../../components/admin/AdminPageHeader'
import CandidateUploadSection from '../../components/admin/CandidateUploadSection'
import ColumnList from '../../components/admin/ColumnList'
import FormModal from '../../components/admin/FormModal'
import RowActions from '../../components/admin/RowActions'
import CandidateAvatar from '../../components/CandidateAvatar'
import SearchBar from '../../components/SearchBar'
import StatusBadge, { wardStatus } from '../../components/StatusBadge'
import Badge from '../../components/ui/Badge'
import Button from '../../components/ui/Button'
import { Card, CardHeader } from '../../components/ui/Card'
import ConfirmDialog from '../../components/ui/ConfirmDialog'
import { Field, Input, Select } from '../../components/ui/Form'
import Pagination, { paginate } from '../../components/ui/Pagination'
import { EmptyState } from '../../components/ui/States'
import Table from '../../components/ui/Table'
import { useForm } from '../../hooks/useForm'
import { useResults } from '../../context/ResultsContext'
import { useCandidateProfile } from '../../context/CandidateProfileContext'
import { useToast } from '../../context/ToastContext'
import { useLanguage } from '../../i18n/I18nContext'
import { allCandidateRows, matchesCandidate, validateCandidateInput } from '../../lib/wards'
import { previewCandidateId } from '../../lib/candidateId'

const PAGE_SIZE = 25
const F = 'admin.candidates.form.'

/** Candidate ID, or a warning badge for an older record whose generated ID collided. */
function CandidateIdCell({ candidate }) {
  const { t } = useLanguage()
  if (candidate.candidateId) return <span className="whitespace-nowrap font-mono text-xs font-semibold text-navy-900">{candidate.candidateId}</span>
  const issue = candidate.idIssue ?? { code: 'ID_CONFLICT' }
  const text = t(`admin.candidates.idIssue.${issue.code}`, { candidateId: issue.candidateId ?? '' })
  return (
    <span title={text}>
      <Badge tone="amber" icon={AlertTriangle}>
        {t('admin.candidates.idMissing')}
      </Badge>
    </span>
  )
}

/** One candidate; the Candidate ID is generated by the server and shown here as a preview. */
function AddCandidateForm({ onClose }) {
  const { t } = useLanguage()
  const notify = useToast()
  const { wardMaster, createCandidate } = useResults()
  const knownWards = useMemo(() => new Set(wardMaster.map((w) => w.wardNo)), [wardMaster])
  const validate = (values) => validateCandidateInput(values, knownWards).errors ?? {}
  const { values, bind, errors, handleSubmit, submitting, formError } = useForm({ name: '', party: '', wardNo: '' }, validate)
  const err = (key) => errors[key] && t(errors[key])
  const idPreview = values.wardNo && values.party.trim() ? previewCandidateId(values.wardNo, values.party) : null

  const save = async (form) => {
    const response = await createCandidate(validateCandidateInput(form, knownWards).record)
    notify(t('admin.candidates.added', { id: response.candidate.candidateId }))
    if (response.reopened?.length) notify(t('admin.results.autoReopened', { wards: response.reopened.join(', ') }), 'warning')
    onClose()
  }

  return (
    <FormModal open onClose={onClose} title={t('admin.candidates.add')} size="md" formId="candidate-add-form" submitLabel={t(`${F}save`)} submitting={submitting} formError={formError}>
      <form id="candidate-add-form" onSubmit={handleSubmit(save)} noValidate className="grid gap-4">
        <Field label={t(`${F}name`)} required error={err('name')}>
          {(p) => <Input {...p} {...bind('name')} autoComplete="off" maxLength={120} />}
        </Field>
        <Field label={t(`${F}party`)} required error={err('party')}>
          {(p) => <Input {...p} {...bind('party')} autoComplete="off" maxLength={80} />}
        </Field>
        <Field label={t(`${F}wardNo`)} required error={err('wardNo')} hint={t(`${F}wardHint`)}>
          {(p) => (
            <Select
              {...p}
              {...bind('wardNo')}
              placeholder={t(`${F}wardSelect`)}
              options={wardMaster.map((w) => ({ value: String(w.wardNo), label: `${t('common.ward', { ward: w.wardNo })}${w.wardName ? ` — ${w.wardName}` : ''}` }))}
            />
          )}
        </Field>
        <div className="rounded-lg bg-slate-50 px-3 py-2.5 text-sm">
          <p className="text-slate-500">{t(`${F}idPreview`)}</p>
          {idPreview?.id ? (
            <p className="mt-0.5 font-mono text-base font-bold text-navy-900">{idPreview.id}</p>
          ) : idPreview?.code ? (
            <p className="mt-0.5 text-amber-800">{t(`admin.candidates.idIssue.${idPreview.code}`)}</p>
          ) : (
            <p className="mt-0.5 text-slate-400">{t(`${F}idPending`)}</p>
          )}
        </div>
      </form>
    </FormModal>
  )
}

/** /admin/candidates — Candidate Master: spreadsheet upload, single add and the candidate overview. */
export default function AdminCandidates() {
  const { t, formatNumber, errorText } = useLanguage()
  const notify = useToast()
  const { wards, wardMaster, deleteCandidate } = useResults()
  const { openProfile } = useCandidateProfile()
  const [dialog, setDialog] = useState(null) // { type: 'add' } | { type: 'delete', candidate }
  const [query, setQuery] = useState('')
  const [page, setPage] = useState(1)
  const close = () => setDialog(null)

  const all = allCandidateRows(wards)
  const q = query.trim()
  const visible = all.filter((c) => matchesCandidate(c, q) || (q && String(c.wardNo) === q.replace(/\D/g, '')))
  const { pageItems, pageCount, current } = paginate(visible, page, PAGE_SIZE)
  const dash = <span className="text-slate-400">—</span>

  const columns = [
    {
      key: 'name',
      header: t('admin.columns.name'),
      render: (c) => (
        <button type="button" onClick={() => openProfile(c.id, { manage: true })} className="flex items-center gap-3 text-left" aria-label={t('result.viewProfile', { name: c.name })}>
          <CandidateAvatar candidate={c} size="sm" />
          <span className="font-semibold text-navy-900 hover:text-brand-700 hover:underline">{c.name}</span>
        </button>
      ),
    },
    { key: 'candidateId', header: t('profile.candidateCode'), render: (c) => <CandidateIdCell candidate={c} /> },
    { key: 'party', header: t('result.party'), render: (c) => c.party },
    { key: 'wardNo', header: t('admin.columns.ward'), className: 'whitespace-nowrap', render: (c) => t('common.ward', { ward: c.wardNo }) },
    { key: 'votes', header: t('admin.columns.totalVotes'), align: 'right', className: 'tabular-nums', render: (c) => (c.totalVotes != null ? formatNumber(c.totalVotes) : dash) },
    { key: 'status', header: t('result.status'), render: (c) => <StatusBadge status={wardStatus({ status: c.wardStatus })} /> },
    {
      key: 'actions',
      header: t('common.actions'),
      align: 'right',
      render: (c) => (
        <div className="flex items-center justify-end gap-1">
          <button
            type="button"
            onClick={() => openProfile(c.id, { manage: true })}
            className="inline-flex h-8 w-8 items-center justify-center rounded-lg text-slate-500 transition-colors hover:bg-slate-100 hover:text-slate-800"
            aria-label={t('result.viewProfile', { name: c.name })}
            title={t('profile.title')}
          >
            <Eye className="h-4 w-4" aria-hidden="true" />
          </button>
          <RowActions label={c.name} onDelete={() => setDialog({ type: 'delete', candidate: c })} />
        </div>
      ),
    },
  ]

  const deleting = dialog?.type === 'delete' ? dialog.candidate : null

  return (
    <>
      <AdminPageHeader
        title={t('admin.candidates.title')}
        description={t('admin.candidates.description')}
        actions={
          <Button icon={Plus} onClick={() => setDialog({ type: 'add' })} disabled={!wardMaster.length}>
            {t('admin.candidates.add')}
          </Button>
        }
      />

      <div className="space-y-6">
        <Card as="section" aria-labelledby="candidate-upload-title">
          <CardHeader title={<span id="candidate-upload-title">{t('admin.candidates.uploadTitle')}</span>} description={<ColumnList required={['Name', 'Party', 'Ward No.']} requiredKey="admin.wards.requiredColumns" />} />
          <div className="p-5">
            <CandidateUploadSection />
          </div>
        </Card>

        <Card as="section" aria-labelledby="candidate-overview-title" className="overflow-hidden">
          <CardHeader title={<span id="candidate-overview-title">{t('admin.candidates.overviewTitle')}</span>} description={t('admin.candidates.overviewHint')} />
          {!all.length ? (
            <EmptyState title={t('admin.candidates.empty')} description={t('admin.candidates.emptyText')} />
          ) : (
            <>
              <div className="flex flex-col gap-3 border-b border-slate-100 p-4 sm:flex-row sm:items-center sm:justify-between">
                <SearchBar
                  id="candidate-search"
                  value={query}
                  onChange={(value) => {
                    setQuery(value)
                    setPage(1)
                  }}
                  placeholder={t('admin.candidates.search')}
                  className="sm:w-80"
                />
                <p className="text-sm text-slate-500" aria-live="polite">
                  {t('admin.candidates.count', { count: formatNumber(visible.length) })}
                </p>
              </div>
              {visible.length ? (
                <>
                  <Table columns={columns} rows={pageItems} rowKey={(c) => c.id} caption={t('admin.candidates.overviewTitle')} />
                  <Pagination page={current} pageCount={pageCount} total={visible.length} pageSize={PAGE_SIZE} onChange={setPage} />
                </>
              ) : (
                <EmptyState />
              )}
            </>
          )}
        </Card>
      </div>

      {dialog?.type === 'add' && <AddCandidateForm onClose={close} />}

      <ConfirmDialog
        open={Boolean(deleting)}
        title={t('admin.candidates.deleteTitle')}
        message={deleting && t('admin.candidates.deleteConfirm', { name: deleting.name, ward: deleting.wardNo })}
        confirmLabel={t('admin.candidates.deleteButton')}
        onConfirm={async () => {
          try {
            const response = await deleteCandidate(deleting.id)
            notify(t('admin.candidates.deleted'))
            if (response.reopened?.length) notify(t('admin.results.autoReopened', { wards: response.reopened.join(', ') }), 'warning')
          } catch (error) {
            if (error.code !== 'UNAUTHORIZED') notify(errorText(error), 'error')
          }
        }}
        onClose={close}
      />
    </>
  )
}
